#!/bin/bash

date
set -x

echo "NUMBER_OF_SERVERS: ${NUMBER_OF_SERVERS:=1}"
echo "DURATION: ${DURATION:=120}"
RESULTS_PATH="${NUMBER_OF_SERVERS}instance(s)"
echo "OUTPUT_PATH: ${OUTPUT_PATH:=/tmp/simulation_results/}"
mkdir -p "$OUTPUT_DIR"
echo "LOAD: ${LOAD:=$((${NUMBER_OF_SERVERS} * 80))}"

echo "SCENARIO: ${SCENARIO}"
echo "DATA_PATH: ${DATA_PATH}"
echo "SERVICE_TIME_FILE_NAME: ${SERVICE_TIME_FILE_NAME}"
echo "SERVICE_TIME_DATA_COLUMN: ${SERVICE_TIME_DATA_COLUMN}"
echo "SIMULATION_NUMBER: ${SIMULATION_NUMBER}"
echo "SHEDDING_FILE_NAME: ${SHEDDING_FILE_NAME}"
echo "SHEDDING_NUMBER_OF_FILES: ${SHEDDING_NUMBER_OF_FILES}"

echo "Simulating..."
MAIN_PATH=$(pwd)/__main__.py
python3 __main__.py $NUMBER_OF_SERVERS $DURATION $SCENARIO $LOAD $RESULTS_PATH $DATA_PATH $SERVICE_TIME_FILE_NAME $SERVICE_TIME_DATA_COLUMN $SIMULATION_NUMBER $SHEDDING_FILE_NAME $SHEDDING_NUMBER_OF_FILES

mv $RESULTS_PATH $OUTPUT_PATH

