#!/bin/bash

date
set -x

echo "NUMBER_OF_SERVERS: ${NUMBER_OF_SERVERS:=1}"
echo "SIM_DURATION_SECONDS: ${SIM_DURATION_SECONDS:=120}"
echo "RESULTS_PATH: ${RESULTS_PATH:=./result}"
echo "LOAD: ${LOAD:=80}"
echo "SCENARIO: ${SCENARIO}"
echo "DATA_PATH: ${DATA_PATH}"
echo "SERVICE_TIME_FILE_NAME: ${SERVICE_TIME_FILE_NAME}"
echo "SERVICE_TIME_DATA_COLUMN: ${SERVICE_TIME_DATA_COLUMN}"
echo "SIMULATION_NUMBER: ${SIMULATION_NUMBER}"
echo "SHEDDING_FILE_NAME: ${SHEDDING_FILE_NAME}"
echo "SHEDDING_NUMBER_OF_FILES: ${SHEDDING_NUMBER_OF_FILES}"

pwd

echo "Simulating..."
MAIN_PATH=$(pwd)/__main__.py
python3 __main__.py $NUMBER_OF_SERVERS $SIM_DURATION_SECONDS $SCENARIO $LOAD $RESULTS_PATH $DATA_PATH $SERVICE_TIME_FILE_NAME $SERVICE_TIME_DATA_COLUMN $SIMULATION_NUMBER $SHEDDING_FILE_NAME $SHEDDING_NUMBER_OF_FILES
