#!/bin/bash

NUMB_OF_SERVERS=$1
SIM_DURATION_SECONDS=$2
SCENARIO=$3
LOAD=$4
RESULTS_PATH=$5

DATA_PATH=$6
SERVICE_TIME_FILE_NAME=$7
SERVICE_TIME_DATA_COLUMN=$8
EXPERIMENT_NUMBER=$9
SHEDDING_FILE_NAME=${10}

echo "Simulating..."
MAIN_PATH=$(pwd)/__main__.py
python3 __main__.py $NUMB_OF_SERVERS $SIM_DURATION_SECONDS $SCENARIO $LOAD $RESULTS_PATH $DATA_PATH $SERVICE_TIME_FILE_NAME $SERVICE_TIME_DATA_COLUMN $EXPERIMENT_NUMBER $SHEDDING_FILE_NAME
