#!/bin/bash

NUMB_OF_SERVERS=$1
SIM_DURATION_SECONDS=$2
SCENARIO=$3
LOAD=$4
RESULTS_PATH=$5
LOG_PATH=$6

echo "Simulating..."
MAIN_PATH=$(pwd)/__main__.py
python3 __main__.py $NUMB_OF_SERVERS $SIM_DURATION_SECONDS $SCENARIO $LOAD $RESULTS_PATH $LOG_PATH